### ISSUE TITLE
required positional argument: 'desc' error

### ISSUE THREAD

**Issue by benstigsen** [martmists/asynctwitch#12]
I get the following error when running it:

> Traceback (most recent call last):
>   File "D:\Projects\Python Projects\asynctwitch-master\bot.py", line 25, in <module>
>     @say.subcommand('this')
>   File "D:\Projects\Python Projects\asynctwitch-master\asynctwitch\dataclasses.py", line 498, in subcommand
>     return SubCommand(self, *args, **kwargs)
> TypeError: __init__() missing 1 required positional argument: 'desc'

**Comment by richarvey** [comment]
If you are using the example change the line from

```
@say.subcommand('this')
```
to
```
@say.subcommand('this', desc='sub command')
```

**Comment by Martmists-GH** [comment]
This entire project will be rewritten, expect the framework to disappear. Instead, see if projects like [Sailor](https://gitlab.com/n303p4/sailor) can be used. I'm willing to accept PRs addressing this after the rewrite.
