### ISSUE TITLE
Error when running something developed off of this

### ISSUE THREAD

**Issue by palmtree5** [martmists/asynctwitch#3]
`Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    prefix = "!",
  File "/usr/local/lib/python3.5/dist-packages/asynctwitch-2.0.0-py3.5.egg/asynctwitch.py", line 606, in __init__
  File "/usr/local/lib/python3.5/dist-packages/asynctwitch-2.0.0-py3.5.egg/asynctwitch.py", line 140, in __init__
AttributeError: module 'asyncio' has no attribute 'ProactorEventLoop'`

I get this error when running something developed with this on Linux. On a quick check of the [documentation](https://docs.python.org/3/library/asyncio-eventloops.html), it seems that may be Windows only

**Comment by Martmists-GH** [comment]
I'll see if I can find out how Linux allows this, and I'll add a check to
see if the OS is Linux or not

**Comment by Martmists-GH** [comment]
Fixed as of 843b06567044ce069dc4d911ed57b19bbd7fc454
